@startuml SE 311 - Assignment 2 Part 1

title
  Sequence Diagram for Part 1
  Aidan Holland (adh346)
endtitle

'https://plantuml.com/sequence-diagram

autonumber

actor User
participant Input
participant CircularShifter
participant Alphabetizer
participant NoiseWordRemoval
participant Output
participant Search

User -> Input: Input text
activate Input
Input -> Input: Validate input
Input -> CircularShifter: Pipe input
deactivate Input
activate CircularShifter
CircularShifter -> CircularShifter: Circular shift
CircularShifter -> Alphabetizer: Pipe circular shifts
deactivate CircularShifter
activate Alphabetizer
Alphabetizer -> Alphabetizer: Alphabetize
Alphabetizer -> NoiseWordRemoval: Pipe alphabetized text
deactivate Alphabetizer
activate NoiseWordRemoval
NoiseWordRemoval -> NoiseWordRemoval: Remove noise words
NoiseWordRemoval -> Output: Pipe text
deactivate NoiseWordRemoval
activate Output
Output -> Output: Output text
Output -> Search: Pipe text
deactivate Output
activate Search
Search -> Search: Search
Output <-- Search: Pipe search results
deactivate Search
activate Output
Output -> Output: Output search results
User <-- Output: Return search results
deactivate Output

@enduml